language: php
php:
  - '7.3'

install:
  - make install

services:
  - postgresql

before_script:
  - psql -c 'create database domains;' -U postgres

script:
  - make db lint test

env:
  global:
  - DB_CONNECTION=pgsql
  - DB_DATABASE=domains
  - DB_USERNAME=postgres
  - DB_PASSWORD=""